<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use function Symfony\Component\Translation\t;

class ProjectResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        //return parent::toArray($request);
        return [
            'project id' => $this->id,
            'name' => $this->name,
            'created_at' => $this->created_at
        ];
    }

    public function with($request)
    {
        //return parent::with($request); // TODO: Change the autogenerated stub
        return[
          'status'=>'Ok'
        ];
    }
}
