<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\Http\Resources\TaskResource;

class ProjectResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        //return parent::toArray($request);
        return [
            'project id' => $this->id,
            'name' => $this->name,
            //getting all tasks belongs to this project.
            'tasks' => TaskResource::collection($this->whenLoaded('tasks')),
            //if task is not Null,it returns tasks count
            'tasks_count' => $this->when(!is_null($this->tasks_count), $this->tasks_count),
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at
        ];
    }

    public function with($request)
    {
        //return parent::with($request); // TODO: Change the autogenerated stub
        return[
          'status'=>'Ok'
        ];
    }
}
